name: Build
on:
  push:
    branches:
      - actions-test
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build ubuntu binary
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.14
      run: cargo build --verbose --release
    - name: Open binary via double-click
      run: chmod +x target/release/slimevr-wrangler
    - name: Archive ubuntu binary
      uses: actions/upload-artifact@v1
      with:
        name: slimevr-wrangler
        path: target/release/slimevr-wrangler